### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by jeffdyer** [graffiticode/api#23]
Listening on 3100...
(node:86039) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [ServerResponse]. Use emitter.setMaxListeners() to increase limit

@KevinDyer I've been seeing this warning in API. Will investigate, but wondering if you're seeing it too, or have an insight. Thanks!

**Comment by KevinDyer** [comment]
I have seen this before, an `EventEmitter` is a lot of calls the `addListener` method in a short amount of time. "By default EventEmitters will print a warning if more than 10 listeners are added for a particular event.". We can use [`setMaxListeners`](https://nodejs.org/dist/latest-v14.x/docs/api/events.html#events_emitter_setmaxlisteners_n) to increase when this warning is logged or set it to `Infinity` to ignore. I would guess this is due to several middlewares listening to the response's `finish` event. I think it is safe to increase max listeners and ignore the warning.

**Comment by jeffdyer** [comment]
Fixed
